# Generated by Django 3.1.2 on 2020-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avaliability_status',
            field=models.CharField(choices=[('IN', 'IN STOCK'), ('OUT', 'OUT OF STOCK')], default='IN', max_length=290),
        ),
    ]
